const { chromium } = require('playwright'); const assert = require('node:assert/strict');
(async () => { const browser = await chromium.launch({ channel: 'msedge', headless: true }); try {
  const page = await browser.newPage(); const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => { window.__responses=[];window.__fail=true;window.desktop={listModels:async()=>({ok:true,models:['test']})};window.codex={connect:async()=>({ok:true}),request:async()=>({ok:true,result:{data:[]}}),notify:async()=>({}),respond:async(id,result)=>{if(window.__delay)await new Promise(resolve=>{window.__finish=resolve});if(window.__fail)return{ok:false,error:'Transport failed'};window.__responses.push({id,result});return{ok:true}},onNotification:()=>()=>{},onServerRequest:fn=>{window.__ask=fn;return()=>{}},onClosed:()=>()=>{},onError:()=>()=>{},onStderr:()=>()=>{}};});
  await page.goto(process.env.FELIX_TEST_URL||'http://127.0.0.1:5318');await page.waitForFunction(()=>window.__ask);
  await page.evaluate(()=>window.__ask({id:1,method:'item/commandExecution/requestApproval',params:{command:'git status',cwd:'D:/repo',availableDecisions:['acceptForSession','decline']}}));
  assert.equal(await page.getByRole('button',{name:'本次允许',exact:true}).count(),0);
  assert.equal(await page.evaluate(()=>document.activeElement.textContent),'本会话允许');
  await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'审批来源');
  await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'拒绝');
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'审批来源');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'本会话允许');
  await page.setViewportSize({width:390,height:720});assert.equal(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
  await page.keyboard.press('Escape'); assert.equal(await page.getByRole('dialog').count(),1);
  await page.evaluate(()=>{document.querySelector('textarea')?.focus();window.__delay=true});
  assert.equal(await page.getByRole('dialog').evaluate(el=>el.contains(document.activeElement)),true);
  await page.getByRole('button',{name:'本会话允许',exact:true}).click();
  await page.keyboard.press('Tab');
  assert.equal(await page.getByRole('dialog').evaluate(el=>el===document.activeElement),true);
  await page.keyboard.press('Control+Shift+P');assert.equal(await page.getByRole('dialog',{name:'命令面板'}).count(),0);
  await page.evaluate(()=>{window.__delay=false;window.__finish()});await page.getByRole('alert').filter({hasText:'Transport failed'}).waitFor();
  await page.evaluate(()=>{window.__fail=false});await page.getByRole('button',{name:'本会话允许',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.deepEqual(await page.evaluate(()=>window.__responses[0]),{id:1,result:{decision:'acceptForSession'}});
  await page.evaluate(()=>window.__ask({id:2,method:'item/permissions/requestApproval',params:{threadId:'a',permissions:{network:{enabled:true}}}}));
  await page.getByText(/enabled/).waitFor();await page.getByRole('button',{name:'拒绝',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.deepEqual(await page.evaluate(()=>window.__responses[1].result),{scope:'turn',permissions:{}});await page.evaluate(()=>window.__ask({id:3,method:'item/permissions/requestApproval',params:{threadId:'a',permissions:{network:{enabled:true},fileSystem:null}}}));
  await page.getByText('本轮允许仅用于当前回合；本会话允许可在此会话后续回合继续使用所列权限。',{exact:true}).waitFor();
  await page.getByRole('button',{name:'本会话允许',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.deepEqual(await page.evaluate(()=>window.__responses[2].result),{scope:'session',permissions:{network:{enabled:true}}});
  await page.evaluate(()=>window.__ask({id:4,method:'item/permissions/requestApproval',params:{threadId:'a',permissions:{network:null,fileSystem:{read:['D:/read'],write:null}}}}));
  await page.getByRole('button',{name:'本轮允许',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.deepEqual(await page.evaluate(()=>window.__responses[3].result),{scope:'turn',permissions:{fileSystem:{read:['D:/read'],write:null}}});
  await page.evaluate(()=>window.__ask({id:5,method:'item/permissions/requestApproval',params:{threadId:'a',permissions:{network:{enabled:true},fileSystem:{read:['D:/read'],write:null}}}}));
  const network=page.getByRole('checkbox',{name:'网络权限',exact:true});const files=page.getByRole('checkbox',{name:'文件系统权限',exact:true});
  await network.uncheck();assert.equal(await files.isChecked(),true);
  await page.getByRole('button',{name:'本会话允许',exact:true}).focus();await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.textContent),'审批来源');await page.keyboard.press('Tab');assert.equal(await network.evaluate(el=>el===document.activeElement),true);
  await page.evaluate(()=>{window.__fail=true;window.__delay=true;});
  await page.getByRole('button',{name:'本会话允许',exact:true}).click();assert.equal(await network.isDisabled(),true);assert.equal(await files.isDisabled(),true);
  await page.evaluate(()=>{window.__delay=false;window.__finish();});await page.getByRole('alert').filter({hasText:'Transport failed'}).waitFor();
  assert.equal(await network.isChecked(),false);assert.equal(await files.isChecked(),true);
  await page.evaluate(()=>{window.__fail=false;});await page.getByRole('button',{name:'本会话允许',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.deepEqual(await page.evaluate(()=>window.__responses[4].result),{scope:'session',permissions:{fileSystem:{read:['D:/read'],write:null}}});
  await page.evaluate(()=>window.__ask({id:6,method:'item/permissions/requestApproval',params:{permissions:{network:{enabled:true}}}}));
  assert.equal(await network.isChecked(),true);await network.uncheck();await page.getByRole('button',{name:'本轮允许',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.deepEqual(await page.evaluate(()=>window.__responses[5].result),{scope:'turn',permissions:{}});
  await page.evaluate(()=>window.__ask({id:7,method:'item/permissions/requestApproval',params:{permissions:{fileSystem:{read:['D:/a'],write:['D:/b'],entries:[{path:{type:'path',path:'D:/a'},access:'read'},{path:{type:'path',path:'D:/b'},access:'write'},{path:{type:'path',path:'D:/secret'},access:'deny'}]}}}}));
  await page.getByRole('checkbox',{name:'写入：D:/b',exact:true}).uncheck();
  const deny=page.getByRole('checkbox',{name:'禁止访问：D:/secret（保留限制）',exact:true});assert.equal(await deny.isDisabled(),true);assert.equal(await deny.isChecked(),true);
  await page.getByRole('button',{name:'本轮允许',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.deepEqual(await page.evaluate(()=>window.__responses[6].result),{scope:'turn',permissions:{fileSystem:{entries:[{path:{type:'path',path:'D:/a'},access:'read'},{path:{type:'path',path:'D:/secret'},access:'deny'}]}}});
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('felix-audit-log-v1')||'[]').filter(item=>item.action==='处理服务请求').length===7);
  const records=await page.evaluate(()=>JSON.parse(localStorage.getItem('felix-audit-log-v1')).filter(item=>item.action==='处理服务请求'));
  assert.equal(records[0].detail,'额外权限 · 本轮 · 网络：未授予 · 文件条目：读取 1 / 写入 0 / 禁止 1');
  assert.equal(records[2].detail,'额外权限 · 本会话 · 网络：未授予 · 文件条目：读取 1 / 写入 0 / 禁止 0');
  assert.ok(!JSON.stringify(records).includes('D:/'));
  assert.deepEqual(errors,[]);console.log('PASS: server decisions, retry after failure, permission details and denial payload');
} finally {await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
