const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { workspaceGit } = require('../electron/workspace-git.cjs');
const { isConflict, conflictPrompt } = require('../src/gitConflicts.ts');
test('all unmerged states are identified; ordinary changes are excluded', () => {
  for (const status of ['DD', 'AU', 'UD', 'UA', 'DU', 'AA', 'UU']) assert.ok(isConflict({ index: status[0], working: status[1] }));
  for (const status of [' M', 'M ', '??', 'D ', 'A ']) assert.equal(isConflict({ index: status[0], working: status[1] }), false);
  assert.match(conflictPrompt('D:/repo', 'main', [{ path: 'a\nb.txt', index: 'U', working: 'U' }]), /"a\\nb.txt"/);
});
test('real merge conflict blocks commit until resolved and staged', async () => {
  const base = path.resolve(__dirname, '../../.project-cache/tmp'); await fs.mkdir(base, { recursive: true });
  const root = await fs.mkdtemp(path.join(base, 'git-conflict-'));
  const git = args => execFileSync('git', args, { cwd: root, windowsHide: true, stdio: 'pipe' }).toString().trim();
  git(['init', '-b', 'main']); git(['config', 'user.name', 'Test']); git(['config', 'user.email', 'test@example.invalid']);
  const commit = async text => { await fs.writeFile(path.join(root, 'a.txt'), text); git(['add', '.']); git(['commit', '-m', text]); };
  await commit('base'); git(['checkout', '-b', 'other']); await commit('other'); git(['checkout', 'main']); await commit('main');
  assert.throws(() => git(['merge', 'other']));
  assert.equal((await workspaceGit({ root, action: 'status' })).files.filter(isConflict).length, 1);
  assert.deepEqual((await workspaceGit({ root, action: 'conflict', path: 'a.txt' })).stages, [{ stage: 1, text: 'base' }, { stage: 2, text: 'main' }, { stage: 3, text: 'other' }]);
  await assert.rejects(workspaceGit({ root, action: 'commit', message: 'premature' }), /冲突/);
  await fs.writeFile(path.join(root, 'a.txt'), 'main and other');
  await workspaceGit({ root, action: 'stage', path: 'a.txt' });
  assert.equal((await workspaceGit({ root, action: 'status' })).files.filter(isConflict).length, 0);
  await workspaceGit({ root, action: 'commit', message: 'resolve both' });
  assert.equal(git(['rev-list', '--parents', '-n', '1', 'HEAD']).split(' ').length, 3);
  git(['checkout', '-b', 'delete-side']); git(['rm', 'a.txt']); git(['commit', '-m', 'delete file']);
  git(['checkout', 'main']); await commit('modified after merge');
  assert.throws(() => git(['merge', 'delete-side']));
  const conflict = (await workspaceGit({ root, action: 'status' })).files.find(isConflict);
  assert.equal(conflict.index + conflict.working, 'UD');
  assert.deepEqual((await workspaceGit({ root, action: 'conflict', path: 'a.txt' })).stages.map(stage => stage.stage), [1, 2]);
  await fs.unlink(path.join(root, 'a.txt'));
  await workspaceGit({ root, action: 'stage', path: 'a.txt' });
  assert.equal((await workspaceGit({ root, action: 'status' })).files.filter(isConflict).length, 0);
  await workspaceGit({ root, action: 'commit', message: 'accept deletion' });
  assert.equal(git(['ls-files', 'a.txt']), '');
  assert.equal(git(['rev-list', '--parents', '-n', '1', 'HEAD']).split(' ').length, 3);
  await fs.writeFile(path.join(root, 'binary.tmp'), Buffer.from([0, 1, 2]));
  await fs.writeFile(path.join(root, 'large.tmp'), 'x'.repeat(512 * 1024 + 1));
  const binary = git(['hash-object', '-w', 'binary.tmp']);
  const large = git(['hash-object', '-w', 'large.tmp']);
  execFileSync('git', ['update-index', '--index-info'], { cwd: root, windowsHide: true, input: `100644 ${binary} 2\tpreview.dat\n100644 ${large} 3\tpreview.dat\n`, stdio: ['pipe', 'pipe', 'pipe'] });
  const previews = (await workspaceGit({ root, action: 'conflict', path: 'preview.dat' })).stages;
  assert.match(previews[0].unavailable, /二进制/);
  assert.match(previews[1].unavailable, /512 KB/);
  assert.ok(previews.every(stage => stage.text === undefined));
});
