const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { workspaceGit } = require('../electron/workspace-git.cjs');
test('fetch and non-forced push respect explicit upstream and divergence', async () => {
  const base = path.resolve(__dirname, '../../.project-cache/tmp');
  await fs.mkdir(base, { recursive: true });
  const scratch = await fs.mkdtemp(path.join(base, 'git-remote-'));
  const root = path.join(scratch, 'work');
  const remote = path.join(scratch, 'remote.git');
  const peer = path.join(scratch, 'peer');
  const git = (cwd, args) => execFileSync('git', args, { cwd, windowsHide: true, encoding: 'utf8', stdio: 'pipe' }).trim();
  await fs.mkdir(root);
  git(root, ['init', '-b', 'main']);
  git(scratch, ['init', '--bare', remote]);
  const identity = cwd => { git(cwd, ['config', 'user.name', 'Test']); git(cwd, ['config', 'user.email', 'test@example.invalid']); };
  identity(root);
  await fs.writeFile(path.join(root, 'base.txt'), 'base');
  git(root, ['add', '.']); git(root, ['commit', '-m', 'base']);
  await assert.rejects(workspaceGit({ root, action: 'push' }), /上游/);
  git(root, ['remote', 'add', 'origin', remote]);
  git(root, ['push', '-u', 'origin', 'main:target']);
  git(scratch, ['clone', '-b', 'target', remote, peer]); identity(peer);
  await fs.writeFile(path.join(root, 'local.txt'), 'local');
  git(root, ['add', '.']); git(root, ['commit', '-m', 'local']);
  let status = await workspaceGit({ root, action: 'status' });
  assert.equal(status.upstream, 'origin/target'); assert.equal(status.ahead, 1); assert.equal(status.behind, 0);
  await workspaceGit({ root, action: 'push' });
  assert.equal(git(remote, ['rev-parse', 'refs/heads/target']), git(root, ['rev-parse', 'HEAD']));
  assert.equal((await workspaceGit({ root, action: 'status' })).ahead, 0);
  await fs.writeFile(path.join(peer, 'peer.txt'), 'peer');
  git(peer, ['add', '.']); git(peer, ['commit', '-m', 'peer']);
  // Create a remote-only history so ordinary push must reject, without forcing.
  git(peer, ['push', 'origin', 'HEAD:other']);
  git(root, ['config', 'branch.main.merge', 'refs/heads/other']);
  await workspaceGit({ root, action: 'fetch' });
  status = await workspaceGit({ root, action: 'status' });
  assert.equal(status.ahead, 1); assert.equal(status.behind, 1);
  const before = git(remote, ['rev-parse', 'refs/heads/other']);
  await assert.rejects(workspaceGit({ root, action: 'push' }), /rejected|non-fast-forward|fetch first/i);
  assert.equal(git(remote, ['rev-parse', 'refs/heads/other']), before);
  git(root, ['checkout', '--detach']);
  assert.equal((await workspaceGit({ root, action: 'status' })).upstream, undefined);
  await assert.rejects(workspaceGit({ root, action: 'push' }), /上游/);
});
