const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { workspaceGit } = require('../electron/workspace-git.cjs');
test('pull fast-forwards explicit upstream and refuses divergent or conflicting work', async () => {
  const base = path.resolve(__dirname, '../../.project-cache/tmp'); await fs.mkdir(base, { recursive: true });
  const scratch = await fs.mkdtemp(path.join(base, 'git-pull-'));
  const root = path.join(scratch, 'work'), remote = path.join(scratch, 'remote.git'), peer = path.join(scratch, 'peer');
  const git = (cwd, args) => execFileSync('git', args, { cwd, windowsHide: true, encoding: 'utf8', stdio: 'pipe' }).trim();
  const identity = cwd => { git(cwd, ['config', 'user.name', 'Test']); git(cwd, ['config', 'user.email', 'test@example.invalid']); };
  await fs.mkdir(root); git(root, ['init', '-b', 'main']); identity(root); git(scratch, ['init', '--bare', remote]);
  await fs.writeFile(path.join(root, 'a.txt'), 'base'); git(root, ['add', '.']); git(root, ['commit', '-m', 'base']);
  await assert.rejects(workspaceGit({ root, action: 'pull', expectedBranch: 'main' }), /上游/);
  git(root, ['checkout', '--detach']);
  await assert.rejects(workspaceGit({ root, action: 'pull', expectedBranch: 'main' }), /游离/);
  git(root, ['checkout', 'main']);
  git(root, ['remote', 'add', 'origin', remote]); git(root, ['push', '-u', 'origin', 'main:target']);
  git(scratch, ['clone', '-b', 'target', remote, peer]); identity(peer);
  const advance = async text => { await fs.writeFile(path.join(peer, 'a.txt'), text); git(peer, ['add', '.']); git(peer, ['commit', '-m', text]); git(peer, ['push']); };
  await advance('remote update');
  await fs.writeFile(path.join(root, 'unrelated.txt'), 'staged local work');
  git(root, ['add', 'unrelated.txt']);
  await assert.rejects(workspaceGit({ root, action: 'pull', expectedBranch: 'stale' }), /分支已变化/);
  let result = await workspaceGit({ root, action: 'pull', expectedBranch: 'main' });
  assert.equal(result.changed, true); assert.equal(result.upstream, 'origin/target');
  assert.equal(git(root, ['rev-parse', 'HEAD']), git(peer, ['rev-parse', 'HEAD']));
  assert.equal(await fs.readFile(path.join(root, 'a.txt'), 'utf8'), 'remote update');
  assert.equal(await fs.readFile(path.join(root, 'unrelated.txt'), 'utf8'), 'staged local work');
  assert.match(git(root, ['diff', '--cached', '--name-only']), /unrelated.txt/);
  assert.equal((await workspaceGit({ root, action: 'pull', expectedBranch: 'main' })).changed, false);
  await advance('second remote');
  await fs.writeFile(path.join(root, 'a.txt'), 'local unsaved');
  git(root, ['config', 'merge.autostash', 'true']);
  const before = git(root, ['rev-parse', 'HEAD']);
  await assert.rejects(workspaceGit({ root, action: 'pull', expectedBranch: 'main' }), /overwritten|local changes/i);
  assert.equal(git(root, ['rev-parse', 'HEAD']), before);
  assert.equal(await fs.readFile(path.join(root, 'a.txt'), 'utf8'), 'local unsaved');
  git(root, ['add', '.']); git(root, ['commit', '-m', 'divergent']);
  const divergent = git(root, ['rev-parse', 'HEAD']);
  await assert.rejects(workspaceGit({ root, action: 'pull', expectedBranch: 'main' }), /fast-forward/i);
  assert.equal(git(root, ['rev-parse', 'HEAD']), divergent);
  assert.equal(git(root, ['status', '--porcelain']), '');
});
