const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { workspaceGit } = require('../electron/workspace-git.cjs');
test('merge upstream preserves both histories, protects local edits and exposes conflicts', async t => {
  const scratch = await fs.mkdtemp(path.join(os.tmpdir(), 'felix-pull-merge-'));
  t.after(() => fs.rm(scratch, { recursive: true, force: true }));
  const root = path.join(scratch, 'work'), remote = path.join(scratch, 'remote.git'), peer = path.join(scratch, 'peer');
  const git = (cwd, ...args) => execFileSync('git', args, { cwd, windowsHide: true, encoding: 'utf8', stdio: 'pipe' }).trim();
  const identity = cwd => { git(cwd, 'config', 'user.name', 'Test'); git(cwd, 'config', 'user.email', 'test@example.invalid'); };
  const commit = async (cwd, name, text) => { await fs.writeFile(path.join(cwd, name), text); git(cwd, 'add', '.'); git(cwd, 'commit', '-m', text); return git(cwd, 'rev-parse', 'HEAD'); };
  await fs.mkdir(root); git(root, 'init', '-b', 'main'); identity(root);
  await commit(root, 'base.txt', 'base'); git(scratch, 'init', '--bare', remote);
  git(root, 'remote', 'add', 'origin', remote); git(root, 'push', '-u', 'origin', 'main:target');
  git(scratch, 'clone', '-b', 'target', remote, peer); identity(peer);
  const local = await commit(root, 'local.txt', 'local');
  const upstream = await commit(peer, 'remote.txt', 'remote'); git(peer, 'push');
  const pull = () => workspaceGit({ root, action: 'pull-merge', expectedBranch: 'main', expectedHead: git(root, 'rev-parse', 'HEAD') });
  await assert.rejects(workspaceGit({ root, action: 'pull-merge', expectedBranch: 'main', expectedHead: 'stale' }), /变化/);
  await fs.writeFile(path.join(root, 'unsaved.txt'), 'keep');
  await assert.rejects(pull(), /工作区/); assert.equal(await fs.readFile(path.join(root, 'unsaved.txt'), 'utf8'), 'keep');
  await fs.unlink(path.join(root, 'unsaved.txt'));
  git(root, 'config', 'merge.ff', 'only');
  const result = await pull(); assert.equal(result.upstream, 'origin/target');
  assert.deepEqual(git(root, 'show', '-s', '--format=%P', 'HEAD').split(' '), [local, upstream]);
  assert.equal((await pull()).changed, false);
  await commit(root, 'base.txt', 'local conflict'); await commit(peer, 'base.txt', 'remote conflict'); git(peer, 'push');
  await assert.rejects(pull(), /CONFLICT|冲突/);
  const status = await workspaceGit({ root, action: 'status' });
  assert.equal(status.merging, true); assert.ok(status.files.some(file => file.index === 'U'));
});
