const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage();
    await page.goto(process.env.FELIX_TEST_URL || 'http://127.0.0.1:5318');
    await page.evaluate(async () => {
      const { default: React } = await import('/node_modules/.vite/deps/react.js');
      const { default: ReactDOM } = await import('/node_modules/.vite/deps/react-dom_client.js');
      const { PreviewText } = await import('/src/PreviewText.tsx');
      const host = document.createElement('div'); document.body.replaceChildren(host);
      const root = ReactDOM.createRoot(host);
      window.__writes = [];
      Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async text => { if (window.__fail) throw Error('denied'); window.__writes.push(text); } } });
      window.__render = (text, truncated = false) => root.render(React.createElement(PreviewText, { text, truncated, ref: React.createRef() }));
      window.__render('First\r\n中文🙂\nlast');
    });
    const pre = page.getByLabel('文件预览文本', { exact: true });
    const copy = page.getByRole('button', { name: '复制预览内容', exact: true });
    await copy.click();
    await page.getByRole('status').getByText('预览内容已复制', { exact: true }).waitFor();
    assert.deepEqual(await page.evaluate(() => window.__writes), ['First\r\n中文🙂\nlast']);
    assert.equal(await pre.textContent(), 'First\r\n中文🙂\nlast');
    await page.getByRole('button', { name: '查找预览内容', exact: true }).click();
    await page.getByRole('textbox', { name: '查找预览内容', exact: true }).fill('中文');
    await page.locator('mark').waitFor();
    assert.equal(await pre.textContent(), 'First\r\n中文🙂\nlast');
    await page.evaluate(() => { window.__fail = true; }); await copy.click();
    await page.getByRole('alert').getByText('复制失败，请检查剪贴板权限后重试。', { exact: true }).waitFor();
    await page.evaluate(() => { window.__fail = false; window.__render('prefix only', true); });
    await page.getByRole('button', { name: '复制已预览部分', exact: true }).click();
    await page.getByRole('status').getByText('已预览部分已复制', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => window.__writes.at(-1)), 'prefix only');
    assert.equal(await pre.textContent(), 'prefix only');
    await page.setViewportSize({ width: 390, height: 844 });
    const longText = 'prefix ' + 'long-path/'.repeat(80) + ' 中文\r\nsecond line\n';
    await page.evaluate(source => window.__render(source), longText);
    await page.waitForFunction(() => document.querySelector('pre').textContent.startsWith('prefix long-path'));
    const wrap = page.getByRole('button', { name: '预览自动换行', exact: true });
    assert.equal(await pre.evaluate(node => node.scrollWidth > node.clientWidth), true);
    await wrap.click();
    assert.equal(await wrap.getAttribute('aria-pressed'), 'true');
    assert.equal(await pre.evaluate(node => node.scrollWidth <= node.clientWidth + 1), true);
    const lineInput = page.getByRole('textbox', { name: '预览行号', exact: true });
    await lineInput.fill('2'); await lineInput.press('Enter');
    assert.equal(await pre.locator('[aria-current=location]').getAttribute('data-line'), '2');
    await page.getByRole('button', { name: '查找预览内容', exact: true }).click();
    await page.getByRole('textbox', { name: '查找预览内容', exact: true }).fill('中文');
    assert.equal(await pre.locator('mark').textContent(), '中文');
    await copy.click();
    await page.waitForFunction(source => window.__writes.at(-1) === source, longText);
    assert.equal(await pre.textContent(), longText);
    await wrap.focus(); await page.keyboard.press('Space');
    assert.equal(await wrap.getAttribute('aria-pressed'), 'false');
    assert.equal(await pre.evaluate(node => node.scrollWidth > node.clientWidth), true);
    await wrap.click();
    await page.evaluate(source => window.__render(source, true), longText);
    await page.getByRole('button', { name: '复制已预览部分', exact: true }).click();
    assert.equal(await wrap.getAttribute('aria-pressed'), 'true');
    assert.equal(await pre.evaluate(node => node.scrollWidth <= node.clientWidth + 1), true);
    await lineInput.fill('4'); await lineInput.press('Enter');
    await page.getByText('请输入 1 至 3 的行号（仅限已预览部分）。', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => window.__writes.at(-1)), longText);
    for (const source of ['', 'ends with newline\n', '\ufeffBOM\r\n', '\n\n']) {
      await page.evaluate(source => window.__render(source), source);
      await copy.click();
      await page.getByRole('status').getByText('预览内容已复制', { exact: true }).waitFor();
      assert.equal(await pre.textContent(), source);
      assert.equal(await page.evaluate(() => window.__writes.at(-1)), source);
    }
    console.log('PASS: preview rendering and copying preserve exact text, highlighting, failed copy and explicit truncated scope');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
