const assert = require('node:assert/strict');
const { applyToolEvent, restoreMessages, finishTools } = require('../src/toolActivity.ts');
const thread = { messages: [] };
const send = (method, extra = {}) => applyToolEvent(thread, 'item/reasoning/' + method, { itemId: 'r', turnId: 't', summaryIndex: 0, ...extra });
send('summaryTextDelta', { summaryIndex: 1, delta: 'second' });
send('summaryTextDelta', { delta: 'first' });
send('summaryPartAdded');
send('summaryTextDelta', { delta: ' part' });
assert.deepEqual(thread.messages[0].tool.rawRecord.item.summary, ['first part', 'second']);
for (const summaryIndex of [-1, 1.2, 1e9, '0']) send('summaryTextDelta', { summaryIndex, delta: 'invalid' });
assert.equal(thread.messages[0].tool.rawRecord.item.summary.length, 2);
applyToolEvent(thread, 'item/completed', { turnId: 't', item: { id: 'r', type: 'reasoning', summary: ['final'], content: ['not summary'] } });
send('summaryTextDelta', { delta: 'late' });
assert.deepEqual(thread.messages[0].tool.rawRecord.item.summary, ['final']);
const restored = restoreMessages([{ turnId: 't', item: { id: 'r', type: 'reasoning', summary: ['history'] } }], thread.messages);
assert.deepEqual(restored[0].tool.rawRecord.item.summary, ['history']);
send('summaryTextDelta', { itemId: 'next', delta: 'unfinished' });
finishTools(thread, 't');
send('summaryTextDelta', { itemId: 'next', delta: 'late' });
assert.deepEqual(thread.messages[1].tool.rawRecord.item.summary, ['unfinished']);
console.log('PASS: reasoning indexed deltas, validation, authoritative completion, history and interruption');
