const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { workspaceFile } = require('../electron/workspace-files.cjs');

test('text edit saves exact UTF-8 bytes and rejects changed files and forbidden paths', async t => {
  const base = path.resolve(__dirname, '../../.project-cache/tmp'); await fs.mkdir(base, { recursive: true });
  const root = await fs.mkdtemp(path.join(base, 'file-edit-')); t.after(() => fs.rm(root, { recursive: true, force: true }));
  const target = path.join(root, 'edit.txt'); await fs.writeFile(target, '\ufeff中文\r\noriginal');
  const read = await workspaceFile(root, 'edit.txt', 'read');
  assert.equal(read.text, '\ufeff中文\r\noriginal');
  const saved = await workspaceFile(root, 'edit.txt', 'write', '', { revision: read.revision, text: '\ufeff中文\r\nupdated' });
  assert.equal(await fs.readFile(target, 'utf8'), saved.text); assert.notEqual(saved.revision, read.revision);
  await fs.writeFile(target, 'external');
  await assert.rejects(workspaceFile(root, 'edit.txt', 'write', '', { revision: saved.revision, text: 'overwrite' }), /外部修改/);
  assert.equal(await fs.readFile(target, 'utf8'), 'external');
  assert.deepEqual(await fs.readdir(root), ['edit.txt']);
  await assert.rejects(workspaceFile(root, '..', 'write', '', { revision: saved.revision, text: 'bad' }), /路径/);
});

test('file search finds nested paths, excludes git, reports result limits and preserves read boundaries', async t => {
  const base = path.resolve(__dirname, '../../.project-cache/tmp'); await fs.mkdir(base, { recursive: true });
  const root = await fs.mkdtemp(path.join(base, 'file-search-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.mkdir(path.join(root, 'src')); await fs.mkdir(path.join(root, '.git'));
  await fs.writeFile(path.join(root, 'src', '中文.TS'), 'source'); await fs.writeFile(path.join(root, '.git', 'secret.ts'), 'hidden');
  const found = await workspaceFile(root, '.', 'search', 'SRC/中文.ts');
  assert.deepEqual(found.entries.map(item => item.path), [path.join('src', '中文.TS')]);
  assert.equal((await workspaceFile(root, '.', 'search', 'secret')).entries.length, 0);
  assert.equal((await workspaceFile(root, '.', 'search', '')).entries.length, 0);
  const outside = await fs.mkdtemp(path.join(base, 'file-search-outside-'));
  t.after(() => fs.rm(outside, { recursive: true, force: true }));
  await fs.writeFile(path.join(outside, 'outside-only.txt'), 'private');
  await fs.symlink(outside, path.join(root, 'linked'), process.platform === 'win32' ? 'junction' : 'dir');
  assert.equal((await workspaceFile(root, '.', 'search', 'outside-only')).entries.length, 0);
  await assert.rejects(workspaceFile(root, 'linked', 'search', 'outside-only'), /路径/);
  await assert.rejects(workspaceFile(root, '..', 'search', 'ts'), /路径/);
  for (let i = 0; i < 202; i++) await fs.writeFile(path.join(root, `match-${i}.txt`), '');
  const limited = await workspaceFile(root, '.', 'search', 'match-');
  assert.equal(limited.entries.length, 200); assert.equal(limited.truncated, true);
});
test('real files: directories, bounded text, binary detection and path boundaries', async t => {
  const base = path.resolve(__dirname, '../../.project-cache/tmp'); await fs.mkdir(base, { recursive: true });
  const root = await fs.mkdtemp(path.join(base, 'file-browser-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.mkdir(path.join(root, 'nested')); await fs.mkdir(path.join(root, '.git'));
  await fs.writeFile(path.join(root, 'text.txt'), 'hello');
  await fs.writeFile(path.join(root, 'large.txt'), 'a'.repeat(300000));
  await fs.writeFile(path.join(root, 'binary.bin'), Buffer.from([0, 1, 2]));
  const listing = await workspaceFile(root);
  assert.equal(listing.entries[0].name, 'nested'); assert.ok(!listing.entries.some(item => item.name === '.git'));
  assert.equal((await workspaceFile(root, 'text.txt', 'read')).text, 'hello');
  const large = await workspaceFile(root, 'large.txt', 'read'); assert.equal(large.text.length, 256 * 1024); assert.equal(large.truncated, true);
  assert.equal((await workspaceFile(root, 'binary.bin', 'read')).binary, true);
  await assert.rejects(workspaceFile(root, '..'), /路径/);
  await assert.rejects(workspaceFile(root, '.git'), /路径/);
  await assert.rejects(workspaceFile(root, 'nested', 'read'), /文件/);
  assert.equal((await workspaceFile(root, 'nested')).entries.length, 0);
  await fs.symlink(path.join(root, 'nested'), path.join(root, 'linked'), process.platform === 'win32' ? 'junction' : 'dir');
  assert.equal((await workspaceFile(root)).entries.find(item => item.name === 'linked').directory, true);
  assert.equal((await workspaceFile(root, 'linked')).entries.length, 0);
  await fs.symlink(base, path.join(root, 'outside'), process.platform === 'win32' ? 'junction' : 'dir');
  await assert.rejects(workspaceFile(root, 'outside'), /路径/);
});
