import { useEffect, useState } from 'react';
import { addRemoteQueuedSubmission, deleteRemoteQueuedSubmission, listRemoteQueuedSubmissions, startRemoteQueuedSubmission } from './codexClient';
import type { RemoteQueuedSubmission } from './threadQueueRemote';
export function RemoteThreadQueuePanel({ threadId, connected, busy }: { threadId?: string; connected: boolean; busy?: boolean }) {
  const [items, setItems] = useState<RemoteQueuedSubmission[]>([]); const [text, setText] = useState(''); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState('');
  const load = async () => { if (!threadId || !connected || busy || loading) return; setLoading(true); setNotice(''); try { setItems(await listRemoteQueuedSubmissions(threadId)); } catch (error) { setNotice(`读取服务端队列失败：${error instanceof Error ? error.message : String(error)}`); } finally { setLoading(false); } };
  useEffect(() => { setItems([]); if (threadId && connected) void load(); }, [threadId, connected]);
  const mutate = async (action: () => Promise<void>, success: string) => { if (loading) return; setLoading(true); setNotice(''); try { await action(); setNotice(success); if (threadId) setItems(await listRemoteQueuedSubmissions(threadId)); } catch (error) { setNotice(`服务端队列操作失败：${error instanceof Error ? error.message : String(error)}`); } finally { setLoading(false); } };
  return <section className="remote-thread-queue" aria-label="服务端排队消息"><header><b>服务端排队消息 · {items.length}</b><button disabled={!threadId || !connected || busy || loading} onClick={() => void load()}>刷新</button></header><form onSubmit={event => { event.preventDefault(); if (!threadId || !text.trim()) return; void mutate(async () => { await addRemoteQueuedSubmission(threadId, text.trim()); setText(''); }, '消息已加入服务端队列'); }}><input aria-label="服务端排队消息" value={text} onChange={event => setText(event.target.value)} placeholder="发送到 app-server 队列" /><button disabled={!threadId || !connected || busy || loading || !text.trim()}>加入队列</button></form>{items.map(item => <div key={item.id}><span>{item.input.map((entry: any) => typeof entry?.text === 'string' ? entry.text : '').filter(Boolean).join(' ') || item.id}</span><button disabled={busy || loading} onClick={() => void mutate(() => deleteRemoteQueuedSubmission(threadId!, item.id), '已删除服务端排队消息')}>删除</button><button disabled={busy || loading} onClick={() => void mutate(() => startRemoteQueuedSubmission(threadId!, item.id), '已启动服务端排队消息')}>启动</button></div>)}{notice && <p role="status">{notice}</p>}</section>;
}
