import { useEffect, useState } from 'react';
import { disableRemoteControl, enableRemoteControl, readRemoteControlClients, readRemoteControlStatusInfo, revokeRemoteControlClient, startRemoteControlPairing, subscribeCodex } from './codexClient';
import type { RemoteControlClient, RemoteControlPairing, RemoteControlStatus } from './remoteControl';

const labels = { disabled: '已停用', connecting: '连接中', connected: '已连接', errored: '错误' } as const;
export function RemoteControlPanel({ connected, busy }: { connected: boolean; busy?: boolean }) {
  const [state, setState] = useState<RemoteControlStatus>(); const [clients, setClients] = useState<RemoteControlClient[]>([]); const [pairing, setPairing] = useState<RemoteControlPairing>(); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState('');
  const load = async () => { if (!connected || busy || loading) return; setLoading(true); setNotice(''); try { const result = await readRemoteControlStatusInfo(); setState(result); setClients(result.environmentId ? await readRemoteControlClients(result.environmentId) : []); } catch (error) { setNotice(`读取远程控制状态失败：${error instanceof Error ? error.message : String(error)}`); } finally { setLoading(false); } };
  useEffect(() => { if (connected) void load(); else { setState(undefined); setClients([]); } }, [connected]);
  useEffect(() => connected ? subscribeCodex({ notification: message => { if (message.method === 'remoteControl/status/changed') void load(); } }) : undefined, [connected]);
  const change = async (action: () => Promise<RemoteControlStatus>, success: string) => { if (loading) return; setLoading(true); setNotice(''); try { const result = await action(); setState(result); setClients(result.environmentId ? await readRemoteControlClients(result.environmentId) : []); setNotice(success); } catch (error) { setNotice(`远程控制操作失败：${error instanceof Error ? error.message : String(error)}`); } finally { setLoading(false); } };
  const pair = async () => { if (loading) return; setLoading(true); setNotice(''); try { setPairing(await startRemoteControlPairing(true)); setNotice('配对码已生成，请在 Codex 客户端输入。'); } catch (error) { setNotice(`生成配对码失败：${error instanceof Error ? error.message : String(error)}`); } finally { setLoading(false); } };
  const revoke = async (client: RemoteControlClient) => { if (!state?.environmentId || loading || !window.confirm(`撤销设备“${client.displayName || client.clientId}”的远程控制权限？`)) return; setLoading(true); setNotice(''); try { await revokeRemoteControlClient(state.environmentId, client.clientId); setClients(await readRemoteControlClients(state.environmentId)); setNotice('设备权限已撤销'); } catch (error) { setNotice(`撤销设备失败：${error instanceof Error ? error.message : String(error)}`); } finally { setLoading(false); } };
  return <section className="settings-card" aria-label="Codex 远程控制"><h2>Codex 远程控制</h2><p>允许已配对的 Codex 客户端远程连接此工作区。</p><p role="status">状态：{state ? labels[state.status] : connected ? '未读取' : '等待连接'}</p><button disabled={!connected || busy || loading} onClick={() => void load()}>刷新状态</button>{state?.status === 'connected' || state?.status === 'connecting' ? <><button disabled={busy || loading} onClick={() => void change(() => disableRemoteControl(false), '远程控制已停用')}>停用</button><button disabled={busy || loading || !state.environmentId} onClick={() => void pair()}>生成配对码</button></> : <button disabled={!connected || busy || loading} onClick={() => void change(() => enableRemoteControl(false), '远程控制已启用')}>启用</button>}{pairing && <div aria-label="远程控制配对信息"><p>配对码：<strong>{pairing.pairingCode}</strong></p>{pairing.manualPairingCode && <p>手动配对码：<strong>{pairing.manualPairingCode}</strong></p>}<small>有效期至 {new Date(pairing.expiresAt * 1000).toLocaleString()}</small></div>}{notice && <p role="status">{notice}</p>}{clients.length > 0 && <ul>{clients.map(client => <li key={client.clientId}><strong>{client.displayName || client.clientId}</strong><span> · {[client.deviceType, client.platform, client.appVersion].filter(Boolean).join(' · ') || '设备信息未提供'}</span><button disabled={loading || busy} onClick={() => void revoke(client)}>撤销</button></li>)}</ul>}</section>;
}
