import { useEffect, useState } from 'react';
import type { Thread } from './domain';
type Goal = NonNullable<Thread['goal']>;
const labels: Record<Goal['status'], string> = { active: '进行中', paused: '已暂停', blocked: '已阻塞', usageLimited: '用量受限', budgetLimited: '预算受限', complete: '已完成' };
export function ThreadGoalPanel({ goal, busy = false, onGet, onSet, onClear }: { goal?: Goal; busy?: boolean; onGet?: () => Promise<void>; onSet?: (input: { objective: string; status: Goal['status']; tokenBudget: number | null }) => Promise<void>; onClear?: () => Promise<void> }) {
  const [editing, setEditing] = useState(!goal); const [objective, setObjective] = useState(goal?.objective || ''); const [status, setStatus] = useState<Goal['status']>(goal?.status || 'active'); const [budget, setBudget] = useState(goal?.tokenBudget == null ? '' : String(goal.tokenBudget));
  useEffect(() => { if (!editing) { setObjective(goal?.objective || ''); setStatus(goal?.status || 'active'); setBudget(goal?.tokenBudget == null ? '' : String(goal.tokenBudget)); } }, [goal, editing]);
  const save = async () => { if (!onSet || !objective.trim()) return; const parsed = budget.trim() === '' ? null : Number(budget); if (parsed !== null && (!Number.isSafeInteger(parsed) || parsed < 0)) return; await onSet({ objective: objective.trim(), status, tokenBudget: parsed }); setEditing(false); };
  return <details className="plan-panel" open><summary>会话目标{goal ? ` · ${labels[goal.status]}` : ' · 未设置'}</summary>{goal && !editing ? <><p style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{goal.objective}</p><small>已用 Token：{goal.tokensUsed.toLocaleString()}{goal.tokenBudget != null ? ` / ${goal.tokenBudget.toLocaleString()}` : ''} · 用时 {goal.timeUsedSeconds.toLocaleString()} 秒</small><div className="plan-actions"><button disabled={busy} onClick={() => setEditing(true)}>编辑</button>{onGet && <button disabled={busy} onClick={() => void onGet()}>刷新</button>}{onClear && <button disabled={busy} onClick={() => void onClear()}>清除目标</button>}</div></> : <div className="goal-editor"><label>目标 <textarea aria-label="会话目标" value={objective} onChange={event => setObjective(event.target.value)} rows={2} /></label><label>状态 <select aria-label="目标状态" value={status} onChange={event => setStatus(event.target.value as Goal['status'])}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Token 预算（可选） <input aria-label="Token 预算" inputMode="numeric" value={budget} onChange={event => setBudget(event.target.value)} placeholder="不限制" /></label><div className="plan-actions"><button disabled={busy || !objective.trim()} onClick={() => void save()}>保存目标</button>{goal && <button disabled={busy} onClick={() => setEditing(false)}>取消</button>}{onGet && <button disabled={busy} onClick={() => void onGet()}>读取远端</button>}</div></div>}</details>;
}
